import { NextRequest, NextResponse } from "next/server";
import { getSupabaseServer } from "@/lib/supabase/server";

// Natural-language search. The AI layer (added later) parses INTENT only:
// asset type, district, size, budget. Rent figures are never generated by a
// model. Results and any numbers come from the verified database.
export async function POST(req: NextRequest) {
  const { query } = (await req.json()) as { query?: string };
  const supabase = getSupabaseServer();
  if (!supabase) return NextResponse.json({ results: [], note: "supabase not configured" });

  const q = (query || "").toLowerCase();
  const assets = ["office", "retail", "warehouse", "land"] as const;
  const asset = assets.find((a) => q.includes(a));

  let sb = supabase.from("listings").select("*").eq("status", "published").limit(24);
  if (asset) sb = sb.eq("asset_type", asset);
  const { data, error } = await sb;
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ parsed: { asset: asset ?? null }, results: data ?? [] });
}
