// src/lib/translate/glossary.ts
//
// Domain term base and do-not-translate list for SAT Markets Arabic translation.
// Brand decision (owner, June 2026): the brand name MAY appear in Arabic in body
// text; only the visual logo stays Latin. So "SAT Markets" is no longer hard-
// protected here. The FAL licence number and URLs remain protected absolutely.

/** English to Arabic term base for commercial real estate (matched case-insensitively). */
export const RE_GLOSSARY: Record<string, string> = {
  "office": "مكتب",
  "office space": "مساحة مكتبية",
  "office floor": "طابق مكتبي",
  "retail": "تجزئة",
  "retail space": "مساحة تجارية",
  "retail unit": "وحدة تجارية",
  "showroom": "صالة عرض",
  "warehouse": "مستودع",
  "logistics": "خدمات لوجستية",
  "logistics shed": "مستودع لوجستي",
  "industrial": "صناعي",
  "clinic": "عيادة",
  "medical clinic": "عيادة طبية",
  "clinic floor": "طابق عيادات",
  "shop": "محل",
  "building": "مبنى",
  "whole building": "مبنى كامل",
  "tower": "برج",
  "land": "أرض",
  "plot": "قطعة أرض",
  "mixed use": "متعدد الاستخدامات",
  "corniche": "الكورنيش",
  "grade a": "الفئة A",
  "grade a+": "الفئة A+",
  "grade b": "الفئة B",
  "shell and core": "هيكل وأساس",
  "fitted": "مجهّز",
  "fully fitted": "مجهّز بالكامل",
  "furnished": "مفروش",
  "unfurnished": "غير مفروش",
  "for rent": "للإيجار",
  "for lease": "للإيجار",
  "for sale": "للبيع",
  "rent": "إيجار",
  "lease": "عقد إيجار",
  "annual rent": "الإيجار السنوي",
  "service charge": "رسوم الخدمات",
  "tenant": "مستأجر",
  "landlord": "مالك",
  "owner": "مالك",
  "broker": "وسيط",
  "verified owner": "موثّق من المالك",
  "available now": "متاح الآن",
  "immediate": "فوري",
  "negotiable": "قابل للتفاوض",
  "covered parking": "مواقف مغطاة",
  "parking": "مواقف",
  "central air conditioning": "تكييف مركزي",
  "central a/c": "تكييف مركزي",
  "air conditioning": "تكييف",
  "elevator": "مصعد",
  "lift": "مصعد",
  "reception": "استقبال",
  "meeting room": "غرفة اجتماعات",
  "meeting rooms": "غرف اجتماعات",
  "pantry": "مطبخ صغير",
  "loading bay": "رصيف تحميل",
  "loading dock": "رصيف تحميل",
  "high ceiling": "سقف مرتفع",
  "clear height": "ارتفاع صافٍ",
  "main road": "شارع رئيسي",
  "corner": "زاوية",
  "ground floor": "الطابق الأرضي",
  "mezzanine": "ميزانين",
  "fiber internet": "إنترنت بالألياف",
  "24/7 security": "أمن على مدار الساعة",
  "facade": "واجهة",
  "frontage": "واجهة",
  "square meter": "متر مربع",
  "square meters": "متر مربع",
  "sqm": "م²",
  "per year": "سنوياً",
  "per month": "شهرياً",
  "sat markets": "سات ماركتس",
  "sat real estate": "سات العقارية",
};

/**
 * Do-not-translate literals. Masked before translation, restored exactly after.
 * The FAL licence number and product URLs must never change. Brand NAMES are no
 * longer here (owner allows them in Arabic text; the logo stays Latin in the UI).
 */
export const DNT_LITERALS: string[] = [
  "1200025510",
  "satmarkets.sa",
  "satestate.com",
];

/** Saudi proper nouns kept in their established Latin form. Extend as needed. */
export const PROPER_NOUNS: string[] = [
  "Al Olaya",
  "Olaya",
  "Al Malqa",
  "Al Malaz",
  "Al Hamra",
  "Ar Rawdah",
  "Al Rawdah",
  "Al Sahafa",
  "As Sahafah",
  "Al Yasmin",
  "Al Wurud",
  "Al Worood",
  "Granada",
  "Al Faisaliyah",
  "Qurtubah",
  "An Narjis",
  "Al Narjis",
  "Al Aqiq",
  "Al Murabba",
  "Diplomatic Quarter",
  "Hittin",
  "KAFD",
  "King Abdullah Financial District",
  "Al Nakheel",
  "King Fahd Road",
  "King Abdulaziz Road",
  "Olaya Street",
  "Tahlia Street",
  "Riyadh",
  "Jeddah",
  "Dammam",
  "Al Khobar",
  "Khobar",
  "Dhahran",
  "Makkah",
  "Mecca",
  "Madinah",
  "Medina",
  "Al Hamra District",
];
