import type { SupabaseClient } from "@supabase/supabase-js";

/**
 * precompatRouteCleanup.ts — the CANONICAL, TESTED source for the cleanup
 * logic embedded in docs/pkg-listing-creation-1b-precompat-route-patch.diff
 * (tenth adversarial review, item 2). This file is not imported by
 * anything in this branch's own application: it exists purely so the
 * patch's own logic runs under this repo's real gate (typecheck, test,
 * lint) before it is prepared as a diff against `main`, rather than being
 * hand-typed directly into a patch file with no coverage of its own. The
 * patch is generated by copying this file's own compiled behaviour
 * (`git apply --check` verified this round against real `main`, see the
 * runbook's own section 11b) alongside a one-line call site added to
 * `main`'s current route.
 *
 * WHY THIS EXISTS, SPECIFICALLY (correcting the prior round's own patch).
 * The prior version of this patch wrapped `storage.remove()` in a bare
 * try/catch with no check of the returned `.error`, and no check of how
 * many objects were actually removed. Verified against this project's own
 * vendored @supabase/storage-js source (2.114.0, StorageFileApi.ts):
 * `.remove()` resolves `{ data: null, error }` for an ordinary API-level
 * failure (a policy refusal, an auth issue) WITHOUT throwing, and can also
 * resolve `{ data: [], error: null }`, a 200 "success" that silently
 * removed nothing at all (a policy-filtered delete, documented at
 * github.com/orgs/supabase/discussions/5786 and
 * github.com/supabase/supabase-js/issues/902, the same shape
 * src/lib/mediaCleanup.ts's own removeStorageObjects() already guards
 * against on this branch). A bare try/catch sees neither.
 *
 * NO DURABLE QUEUE. `main`, as it stands, has no media_cleanup_queue table
 * (it is one of this package's own not-yet-applied migrations) and no
 * service-role client wired into this route today. The only observable
 * fallback available to a patch this minimal is a structured, greppable
 * `console.error` line for every failure shape, which this function always
 * produces on any outcome other than a confirmed, full removal. This is
 * not a promise the object will ever actually be found and cleaned up:
 * it is only a signal an operator (or, once this package's own migrations
 * and scripts/sweep-unreferenced-media-objects.mjs are both live, that
 * script's own later scan) can act on. Do not read this file, or the
 * patch it produces, as guaranteeing eventual discovery.
 */
export async function cleanUpOldRouteObjectOnInsertFailure(sb: SupabaseClient, objectKey: string): Promise<void> {
  try {
    const { data, error } = await sb.storage.from("listing-media").remove([objectKey]);
    if (error) {
      console.error("[precompat-cleanup] storage.remove returned an error; the uploaded object may still be orphaned and is not durably tracked anywhere", {
        objectKey,
        error: error.message,
      });
      return;
    }
    if ((data ?? []).length !== 1) {
      console.error("[precompat-cleanup] storage.remove reported success but removed nothing (a policy-filtered no-op); the uploaded object is likely still orphaned and is not durably tracked anywhere", {
        objectKey,
        removedCount: (data ?? []).length,
      });
    }
  } catch (e) {
    console.error("[precompat-cleanup] storage.remove threw; the uploaded object may still be orphaned and is not durably tracked anywhere", {
      objectKey,
      error: e instanceof Error ? e.message : String(e),
    });
  }
}

/**
 * Pinned, literal copy of the real, current response this route already
 * returns on an insert failure (verified via `git show origin/main:src/
 * app/api/listings/[id]/media/route.ts`). Not used by the function above,
 * and not called at this route's own call site either: it exists only so
 * a test can assert, by direct comparison, that the one added cleanup
 * line above is a pure side effect, never plumbed into what the caller
 * returns to the user, regardless of cleanup outcome.
 */
export const OLD_ROUTE_ATTACH_FAILED_RESPONSE = {
  status: 400,
  body: { error: "Saved the file but could not attach it.", code: "attach_failed" },
} as const;
